/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 16
#define LARGE_STATE_COUNT 12
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 36
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  anon_sym_COLON = 2,
  aux_sym_opcode_no_arg_token1 = 3,
  aux_sym_opcode_no_arg_token2 = 4,
  aux_sym_opcode_no_arg_token3 = 5,
  aux_sym_opcode_no_arg_token4 = 6,
  aux_sym_opcode_no_arg_token5 = 7,
  aux_sym_opcode_no_arg_token6 = 8,
  aux_sym_opcode_no_arg_token7 = 9,
  aux_sym_opcode_no_arg_token8 = 10,
  aux_sym_opcode_no_arg_token9 = 11,
  aux_sym_opcode_no_arg_token10 = 12,
  aux_sym_opcode_no_arg_token11 = 13,
  aux_sym_opcode_no_arg_token12 = 14,
  aux_sym_opcode_no_arg_token13 = 15,
  aux_sym_opcode_no_arg_token14 = 16,
  aux_sym_opcode_no_arg_token15 = 17,
  aux_sym_opcode_no_arg_token16 = 18,
  aux_sym_opcode_no_arg_token17 = 19,
  aux_sym_opcode_no_arg_token18 = 20,
  aux_sym_opcode_no_arg_token19 = 21,
  aux_sym_opcode_with_arg_token1 = 22,
  aux_sym_opcode_with_arg_token2 = 23,
  aux_sym_opcode_with_arg_token3 = 24,
  aux_sym_opcode_with_arg_token4 = 25,
  aux_sym_opcode_with_arg_token5 = 26,
  aux_sym_opcode_with_arg_token6 = 27,
  aux_sym_opcode_with_arg_token7 = 28,
  aux_sym_opcode_with_arg_token8 = 29,
  aux_sym_opcode_jump_token1 = 30,
  aux_sym_opcode_jump_token2 = 31,
  aux_sym_opcode_jump_token3 = 32,
  sym_identifier = 33,
  aux_sym_number_token1 = 34,
  aux_sym_number_token2 = 35,
  sym_source_file = 36,
  sym__item = 37,
  sym_label_definition = 38,
  sym_instruction = 39,
  sym_argument = 40,
  sym_syscall_arg = 41,
  sym_opcode_no_arg = 42,
  sym_opcode_with_arg = 43,
  sym_opcode_jump = 44,
  sym_number = 45,
  aux_sym_source_file_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [anon_sym_COLON] = ":",
  [aux_sym_opcode_no_arg_token1] = "opcode_no_arg_token1",
  [aux_sym_opcode_no_arg_token2] = "opcode_no_arg_token2",
  [aux_sym_opcode_no_arg_token3] = "opcode_no_arg_token3",
  [aux_sym_opcode_no_arg_token4] = "opcode_no_arg_token4",
  [aux_sym_opcode_no_arg_token5] = "opcode_no_arg_token5",
  [aux_sym_opcode_no_arg_token6] = "opcode_no_arg_token6",
  [aux_sym_opcode_no_arg_token7] = "opcode_no_arg_token7",
  [aux_sym_opcode_no_arg_token8] = "opcode_no_arg_token8",
  [aux_sym_opcode_no_arg_token9] = "opcode_no_arg_token9",
  [aux_sym_opcode_no_arg_token10] = "opcode_no_arg_token10",
  [aux_sym_opcode_no_arg_token11] = "opcode_no_arg_token11",
  [aux_sym_opcode_no_arg_token12] = "opcode_no_arg_token12",
  [aux_sym_opcode_no_arg_token13] = "opcode_no_arg_token13",
  [aux_sym_opcode_no_arg_token14] = "opcode_no_arg_token14",
  [aux_sym_opcode_no_arg_token15] = "opcode_no_arg_token15",
  [aux_sym_opcode_no_arg_token16] = "opcode_no_arg_token16",
  [aux_sym_opcode_no_arg_token17] = "opcode_no_arg_token17",
  [aux_sym_opcode_no_arg_token18] = "opcode_no_arg_token18",
  [aux_sym_opcode_no_arg_token19] = "opcode_no_arg_token19",
  [aux_sym_opcode_with_arg_token1] = "opcode_with_arg_token1",
  [aux_sym_opcode_with_arg_token2] = "opcode_with_arg_token2",
  [aux_sym_opcode_with_arg_token3] = "opcode_with_arg_token3",
  [aux_sym_opcode_with_arg_token4] = "opcode_with_arg_token4",
  [aux_sym_opcode_with_arg_token5] = "opcode_with_arg_token5",
  [aux_sym_opcode_with_arg_token6] = "opcode_with_arg_token6",
  [aux_sym_opcode_with_arg_token7] = "opcode_with_arg_token7",
  [aux_sym_opcode_with_arg_token8] = "opcode_with_arg_token8",
  [aux_sym_opcode_jump_token1] = "opcode_jump_token1",
  [aux_sym_opcode_jump_token2] = "opcode_jump_token2",
  [aux_sym_opcode_jump_token3] = "opcode_jump_token3",
  [sym_identifier] = "identifier",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_label_definition] = "label_definition",
  [sym_instruction] = "instruction",
  [sym_argument] = "argument",
  [sym_syscall_arg] = "syscall_arg",
  [sym_opcode_no_arg] = "opcode_no_arg",
  [sym_opcode_with_arg] = "opcode_with_arg",
  [sym_opcode_jump] = "opcode_jump",
  [sym_number] = "number",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym_opcode_no_arg_token1] = aux_sym_opcode_no_arg_token1,
  [aux_sym_opcode_no_arg_token2] = aux_sym_opcode_no_arg_token2,
  [aux_sym_opcode_no_arg_token3] = aux_sym_opcode_no_arg_token3,
  [aux_sym_opcode_no_arg_token4] = aux_sym_opcode_no_arg_token4,
  [aux_sym_opcode_no_arg_token5] = aux_sym_opcode_no_arg_token5,
  [aux_sym_opcode_no_arg_token6] = aux_sym_opcode_no_arg_token6,
  [aux_sym_opcode_no_arg_token7] = aux_sym_opcode_no_arg_token7,
  [aux_sym_opcode_no_arg_token8] = aux_sym_opcode_no_arg_token8,
  [aux_sym_opcode_no_arg_token9] = aux_sym_opcode_no_arg_token9,
  [aux_sym_opcode_no_arg_token10] = aux_sym_opcode_no_arg_token10,
  [aux_sym_opcode_no_arg_token11] = aux_sym_opcode_no_arg_token11,
  [aux_sym_opcode_no_arg_token12] = aux_sym_opcode_no_arg_token12,
  [aux_sym_opcode_no_arg_token13] = aux_sym_opcode_no_arg_token13,
  [aux_sym_opcode_no_arg_token14] = aux_sym_opcode_no_arg_token14,
  [aux_sym_opcode_no_arg_token15] = aux_sym_opcode_no_arg_token15,
  [aux_sym_opcode_no_arg_token16] = aux_sym_opcode_no_arg_token16,
  [aux_sym_opcode_no_arg_token17] = aux_sym_opcode_no_arg_token17,
  [aux_sym_opcode_no_arg_token18] = aux_sym_opcode_no_arg_token18,
  [aux_sym_opcode_no_arg_token19] = aux_sym_opcode_no_arg_token19,
  [aux_sym_opcode_with_arg_token1] = aux_sym_opcode_with_arg_token1,
  [aux_sym_opcode_with_arg_token2] = aux_sym_opcode_with_arg_token2,
  [aux_sym_opcode_with_arg_token3] = aux_sym_opcode_with_arg_token3,
  [aux_sym_opcode_with_arg_token4] = aux_sym_opcode_with_arg_token4,
  [aux_sym_opcode_with_arg_token5] = aux_sym_opcode_with_arg_token5,
  [aux_sym_opcode_with_arg_token6] = aux_sym_opcode_with_arg_token6,
  [aux_sym_opcode_with_arg_token7] = aux_sym_opcode_with_arg_token7,
  [aux_sym_opcode_with_arg_token8] = aux_sym_opcode_with_arg_token8,
  [aux_sym_opcode_jump_token1] = aux_sym_opcode_jump_token1,
  [aux_sym_opcode_jump_token2] = aux_sym_opcode_jump_token2,
  [aux_sym_opcode_jump_token3] = aux_sym_opcode_jump_token3,
  [sym_identifier] = sym_identifier,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_label_definition] = sym_label_definition,
  [sym_instruction] = sym_instruction,
  [sym_argument] = sym_argument,
  [sym_syscall_arg] = sym_syscall_arg,
  [sym_opcode_no_arg] = sym_opcode_no_arg,
  [sym_opcode_with_arg] = sym_opcode_with_arg,
  [sym_opcode_jump] = sym_opcode_jump,
  [sym_number] = sym_number,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token5] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token6] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token7] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token8] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token9] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token10] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token11] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token12] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token13] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token14] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token15] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token16] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token17] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token18] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_no_arg_token19] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_with_arg_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_with_arg_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_with_arg_token3] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_with_arg_token4] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_with_arg_token5] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_with_arg_token6] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_with_arg_token7] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_with_arg_token8] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_jump_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_jump_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_opcode_jump_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_label_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_syscall_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_opcode_no_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_opcode_with_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_opcode_jump] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      ADVANCE_MAP(
        '0', 77,
        ':', 5,
        ';', 4,
        'A', 45,
        'a', 45,
        'C', 36,
        'c', 36,
        'D', 52,
        'd', 52,
        'E', 67,
        'e', 67,
        'F', 53,
        'f', 53,
        'G', 46,
        'g', 46,
        'J', 59,
        'j', 59,
        'L', 47,
        'l', 47,
        'M', 63,
        'm', 63,
        'N', 50,
        'n', 50,
        'P', 62,
        'p', 62,
        'R', 48,
        'r', 48,
        'S', 72,
        's', 72,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(78);
      if (('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 1:
      if (lookahead == '0') ADVANCE(77);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(78);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(79);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token5);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token6);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token7);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token8);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(29);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token9);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token12);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token13);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_opcode_no_arg_token19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_opcode_with_arg_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_opcode_with_arg_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_opcode_with_arg_token3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_opcode_with_arg_token4);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_opcode_with_arg_token5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_opcode_with_arg_token6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_opcode_with_arg_token7);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_opcode_with_arg_token8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_opcode_jump_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_opcode_jump_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_opcode_jump_token3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(24);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(22);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(38);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(74);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'M' ||
          lookahead == 'm') ADVANCE(75);
      if (lookahead == 'Z' ||
          lookahead == 'z') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Y') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(76);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(65);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(43);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'Q' ||
          lookahead == 'q') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'Q' ||
          lookahead == 'q') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      ADVANCE_MAP(
        'T', 61,
        't', 61,
        'U', 40,
        'u', 40,
        'W', 37,
        'w', 37,
        'Y', 71,
        'y', 71,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'V' ||
          lookahead == 'v') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'Z' ||
          lookahead == 'z') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Y') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'y')) ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(79);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token1] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token2] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token3] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token4] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token5] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token6] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token7] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token8] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token9] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token10] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token11] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token12] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token13] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token14] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token15] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token16] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token17] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token18] = ACTIONS(1),
    [aux_sym_opcode_no_arg_token19] = ACTIONS(1),
    [aux_sym_opcode_with_arg_token1] = ACTIONS(1),
    [aux_sym_opcode_with_arg_token2] = ACTIONS(1),
    [aux_sym_opcode_with_arg_token3] = ACTIONS(1),
    [aux_sym_opcode_with_arg_token4] = ACTIONS(1),
    [aux_sym_opcode_with_arg_token5] = ACTIONS(1),
    [aux_sym_opcode_with_arg_token6] = ACTIONS(1),
    [aux_sym_opcode_with_arg_token7] = ACTIONS(1),
    [aux_sym_opcode_with_arg_token8] = ACTIONS(1),
    [aux_sym_opcode_jump_token1] = ACTIONS(1),
    [aux_sym_opcode_jump_token2] = ACTIONS(1),
    [aux_sym_opcode_jump_token3] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_number_token2] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(15),
    [sym__item] = STATE(2),
    [sym_label_definition] = STATE(2),
    [sym_instruction] = STATE(2),
    [sym_argument] = STATE(7),
    [sym_syscall_arg] = STATE(2),
    [sym_opcode_no_arg] = STATE(8),
    [sym_opcode_with_arg] = STATE(12),
    [sym_opcode_jump] = STATE(12),
    [sym_number] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [aux_sym_opcode_no_arg_token1] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token2] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token3] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token4] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token5] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token6] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token7] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token8] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token9] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token10] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token11] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token12] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token13] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token14] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token15] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token16] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token17] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token18] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token19] = ACTIONS(7),
    [aux_sym_opcode_with_arg_token1] = ACTIONS(9),
    [aux_sym_opcode_with_arg_token2] = ACTIONS(9),
    [aux_sym_opcode_with_arg_token3] = ACTIONS(9),
    [aux_sym_opcode_with_arg_token4] = ACTIONS(9),
    [aux_sym_opcode_with_arg_token5] = ACTIONS(9),
    [aux_sym_opcode_with_arg_token6] = ACTIONS(9),
    [aux_sym_opcode_with_arg_token7] = ACTIONS(9),
    [aux_sym_opcode_with_arg_token8] = ACTIONS(9),
    [aux_sym_opcode_jump_token1] = ACTIONS(11),
    [aux_sym_opcode_jump_token2] = ACTIONS(11),
    [aux_sym_opcode_jump_token3] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
  },
  [STATE(2)] = {
    [sym__item] = STATE(3),
    [sym_label_definition] = STATE(3),
    [sym_instruction] = STATE(3),
    [sym_argument] = STATE(7),
    [sym_syscall_arg] = STATE(3),
    [sym_opcode_no_arg] = STATE(8),
    [sym_opcode_with_arg] = STATE(12),
    [sym_opcode_jump] = STATE(12),
    [sym_number] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_comment] = ACTIONS(21),
    [aux_sym_opcode_no_arg_token1] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token2] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token3] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token4] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token5] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token6] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token7] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token8] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token9] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token10] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token11] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token12] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token13] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token14] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token15] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token16] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token17] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token18] = ACTIONS(7),
    [aux_sym_opcode_no_arg_token19] = ACTIONS(7),
    [aux_sym_opcode_with_arg_token1] = ACTIONS(9),
    [aux_sym_opcode_with_arg_token2] = ACTIONS(9),
    [aux_sym_opcode_with_arg_token3] = ACTIONS(9),
    [aux_sym_opcode_with_arg_token4] = ACTIONS(9),
    [aux_sym_opcode_with_arg_token5] = ACTIONS(9),
    [aux_sym_opcode_with_arg_token6] = ACTIONS(9),
    [aux_sym_opcode_with_arg_token7] = ACTIONS(9),
    [aux_sym_opcode_with_arg_token8] = ACTIONS(9),
    [aux_sym_opcode_jump_token1] = ACTIONS(11),
    [aux_sym_opcode_jump_token2] = ACTIONS(11),
    [aux_sym_opcode_jump_token3] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
    [aux_sym_number_token1] = ACTIONS(15),
    [aux_sym_number_token2] = ACTIONS(17),
  },
  [STATE(3)] = {
    [sym__item] = STATE(3),
    [sym_label_definition] = STATE(3),
    [sym_instruction] = STATE(3),
    [sym_argument] = STATE(7),
    [sym_syscall_arg] = STATE(3),
    [sym_opcode_no_arg] = STATE(8),
    [sym_opcode_with_arg] = STATE(12),
    [sym_opcode_jump] = STATE(12),
    [sym_number] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_comment] = ACTIONS(25),
    [aux_sym_opcode_no_arg_token1] = ACTIONS(28),
    [aux_sym_opcode_no_arg_token2] = ACTIONS(28),
    [aux_sym_opcode_no_arg_token3] = ACTIONS(28),
    [aux_sym_opcode_no_arg_token4] = ACTIONS(28),
    [aux_sym_opcode_no_arg_token5] = ACTIONS(28),
    [aux_sym_opcode_no_arg_token6] = ACTIONS(28),
    [aux_sym_opcode_no_arg_token7] = ACTIONS(28),
    [aux_sym_opcode_no_arg_token8] = ACTIONS(28),
    [aux_sym_opcode_no_arg_token9] = ACTIONS(28),
    [aux_sym_opcode_no_arg_token10] = ACTIONS(28),
    [aux_sym_opcode_no_arg_token11] = ACTIONS(28),
    [aux_sym_opcode_no_arg_token12] = ACTIONS(28),
    [aux_sym_opcode_no_arg_token13] = ACTIONS(28),
    [aux_sym_opcode_no_arg_token14] = ACTIONS(28),
    [aux_sym_opcode_no_arg_token15] = ACTIONS(28),
    [aux_sym_opcode_no_arg_token16] = ACTIONS(28),
    [aux_sym_opcode_no_arg_token17] = ACTIONS(28),
    [aux_sym_opcode_no_arg_token18] = ACTIONS(28),
    [aux_sym_opcode_no_arg_token19] = ACTIONS(28),
    [aux_sym_opcode_with_arg_token1] = ACTIONS(31),
    [aux_sym_opcode_with_arg_token2] = ACTIONS(31),
    [aux_sym_opcode_with_arg_token3] = ACTIONS(31),
    [aux_sym_opcode_with_arg_token4] = ACTIONS(31),
    [aux_sym_opcode_with_arg_token5] = ACTIONS(31),
    [aux_sym_opcode_with_arg_token6] = ACTIONS(31),
    [aux_sym_opcode_with_arg_token7] = ACTIONS(31),
    [aux_sym_opcode_with_arg_token8] = ACTIONS(31),
    [aux_sym_opcode_jump_token1] = ACTIONS(34),
    [aux_sym_opcode_jump_token2] = ACTIONS(34),
    [aux_sym_opcode_jump_token3] = ACTIONS(34),
    [sym_identifier] = ACTIONS(37),
    [aux_sym_number_token1] = ACTIONS(40),
    [aux_sym_number_token2] = ACTIONS(43),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(46),
    [sym_comment] = ACTIONS(46),
    [anon_sym_COLON] = ACTIONS(48),
    [aux_sym_opcode_no_arg_token1] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token2] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token3] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token4] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token5] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token6] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token7] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token8] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token9] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token10] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token11] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token12] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token13] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token14] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token15] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token16] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token17] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token18] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token19] = ACTIONS(50),
    [aux_sym_opcode_with_arg_token1] = ACTIONS(50),
    [aux_sym_opcode_with_arg_token2] = ACTIONS(50),
    [aux_sym_opcode_with_arg_token3] = ACTIONS(50),
    [aux_sym_opcode_with_arg_token4] = ACTIONS(50),
    [aux_sym_opcode_with_arg_token5] = ACTIONS(50),
    [aux_sym_opcode_with_arg_token6] = ACTIONS(50),
    [aux_sym_opcode_with_arg_token7] = ACTIONS(50),
    [aux_sym_opcode_with_arg_token8] = ACTIONS(50),
    [aux_sym_opcode_jump_token1] = ACTIONS(50),
    [aux_sym_opcode_jump_token2] = ACTIONS(50),
    [aux_sym_opcode_jump_token3] = ACTIONS(50),
    [sym_identifier] = ACTIONS(50),
    [aux_sym_number_token1] = ACTIONS(50),
    [aux_sym_number_token2] = ACTIONS(46),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(52),
    [sym_comment] = ACTIONS(52),
    [aux_sym_opcode_no_arg_token1] = ACTIONS(54),
    [aux_sym_opcode_no_arg_token2] = ACTIONS(54),
    [aux_sym_opcode_no_arg_token3] = ACTIONS(54),
    [aux_sym_opcode_no_arg_token4] = ACTIONS(54),
    [aux_sym_opcode_no_arg_token5] = ACTIONS(54),
    [aux_sym_opcode_no_arg_token6] = ACTIONS(54),
    [aux_sym_opcode_no_arg_token7] = ACTIONS(54),
    [aux_sym_opcode_no_arg_token8] = ACTIONS(54),
    [aux_sym_opcode_no_arg_token9] = ACTIONS(54),
    [aux_sym_opcode_no_arg_token10] = ACTIONS(54),
    [aux_sym_opcode_no_arg_token11] = ACTIONS(54),
    [aux_sym_opcode_no_arg_token12] = ACTIONS(54),
    [aux_sym_opcode_no_arg_token13] = ACTIONS(54),
    [aux_sym_opcode_no_arg_token14] = ACTIONS(54),
    [aux_sym_opcode_no_arg_token15] = ACTIONS(54),
    [aux_sym_opcode_no_arg_token16] = ACTIONS(54),
    [aux_sym_opcode_no_arg_token17] = ACTIONS(54),
    [aux_sym_opcode_no_arg_token18] = ACTIONS(54),
    [aux_sym_opcode_no_arg_token19] = ACTIONS(54),
    [aux_sym_opcode_with_arg_token1] = ACTIONS(54),
    [aux_sym_opcode_with_arg_token2] = ACTIONS(54),
    [aux_sym_opcode_with_arg_token3] = ACTIONS(54),
    [aux_sym_opcode_with_arg_token4] = ACTIONS(54),
    [aux_sym_opcode_with_arg_token5] = ACTIONS(54),
    [aux_sym_opcode_with_arg_token6] = ACTIONS(54),
    [aux_sym_opcode_with_arg_token7] = ACTIONS(54),
    [aux_sym_opcode_with_arg_token8] = ACTIONS(54),
    [aux_sym_opcode_jump_token1] = ACTIONS(54),
    [aux_sym_opcode_jump_token2] = ACTIONS(54),
    [aux_sym_opcode_jump_token3] = ACTIONS(54),
    [sym_identifier] = ACTIONS(54),
    [aux_sym_number_token1] = ACTIONS(54),
    [aux_sym_number_token2] = ACTIONS(52),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(56),
    [sym_comment] = ACTIONS(56),
    [aux_sym_opcode_no_arg_token1] = ACTIONS(58),
    [aux_sym_opcode_no_arg_token2] = ACTIONS(58),
    [aux_sym_opcode_no_arg_token3] = ACTIONS(58),
    [aux_sym_opcode_no_arg_token4] = ACTIONS(58),
    [aux_sym_opcode_no_arg_token5] = ACTIONS(58),
    [aux_sym_opcode_no_arg_token6] = ACTIONS(58),
    [aux_sym_opcode_no_arg_token7] = ACTIONS(58),
    [aux_sym_opcode_no_arg_token8] = ACTIONS(58),
    [aux_sym_opcode_no_arg_token9] = ACTIONS(58),
    [aux_sym_opcode_no_arg_token10] = ACTIONS(58),
    [aux_sym_opcode_no_arg_token11] = ACTIONS(58),
    [aux_sym_opcode_no_arg_token12] = ACTIONS(58),
    [aux_sym_opcode_no_arg_token13] = ACTIONS(58),
    [aux_sym_opcode_no_arg_token14] = ACTIONS(58),
    [aux_sym_opcode_no_arg_token15] = ACTIONS(58),
    [aux_sym_opcode_no_arg_token16] = ACTIONS(58),
    [aux_sym_opcode_no_arg_token17] = ACTIONS(58),
    [aux_sym_opcode_no_arg_token18] = ACTIONS(58),
    [aux_sym_opcode_no_arg_token19] = ACTIONS(58),
    [aux_sym_opcode_with_arg_token1] = ACTIONS(58),
    [aux_sym_opcode_with_arg_token2] = ACTIONS(58),
    [aux_sym_opcode_with_arg_token3] = ACTIONS(58),
    [aux_sym_opcode_with_arg_token4] = ACTIONS(58),
    [aux_sym_opcode_with_arg_token5] = ACTIONS(58),
    [aux_sym_opcode_with_arg_token6] = ACTIONS(58),
    [aux_sym_opcode_with_arg_token7] = ACTIONS(58),
    [aux_sym_opcode_with_arg_token8] = ACTIONS(58),
    [aux_sym_opcode_jump_token1] = ACTIONS(58),
    [aux_sym_opcode_jump_token2] = ACTIONS(58),
    [aux_sym_opcode_jump_token3] = ACTIONS(58),
    [sym_identifier] = ACTIONS(58),
    [aux_sym_number_token1] = ACTIONS(58),
    [aux_sym_number_token2] = ACTIONS(56),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(60),
    [sym_comment] = ACTIONS(60),
    [aux_sym_opcode_no_arg_token1] = ACTIONS(62),
    [aux_sym_opcode_no_arg_token2] = ACTIONS(62),
    [aux_sym_opcode_no_arg_token3] = ACTIONS(62),
    [aux_sym_opcode_no_arg_token4] = ACTIONS(62),
    [aux_sym_opcode_no_arg_token5] = ACTIONS(62),
    [aux_sym_opcode_no_arg_token6] = ACTIONS(62),
    [aux_sym_opcode_no_arg_token7] = ACTIONS(62),
    [aux_sym_opcode_no_arg_token8] = ACTIONS(62),
    [aux_sym_opcode_no_arg_token9] = ACTIONS(62),
    [aux_sym_opcode_no_arg_token10] = ACTIONS(62),
    [aux_sym_opcode_no_arg_token11] = ACTIONS(62),
    [aux_sym_opcode_no_arg_token12] = ACTIONS(62),
    [aux_sym_opcode_no_arg_token13] = ACTIONS(62),
    [aux_sym_opcode_no_arg_token14] = ACTIONS(62),
    [aux_sym_opcode_no_arg_token15] = ACTIONS(62),
    [aux_sym_opcode_no_arg_token16] = ACTIONS(62),
    [aux_sym_opcode_no_arg_token17] = ACTIONS(62),
    [aux_sym_opcode_no_arg_token18] = ACTIONS(62),
    [aux_sym_opcode_no_arg_token19] = ACTIONS(62),
    [aux_sym_opcode_with_arg_token1] = ACTIONS(62),
    [aux_sym_opcode_with_arg_token2] = ACTIONS(62),
    [aux_sym_opcode_with_arg_token3] = ACTIONS(62),
    [aux_sym_opcode_with_arg_token4] = ACTIONS(62),
    [aux_sym_opcode_with_arg_token5] = ACTIONS(62),
    [aux_sym_opcode_with_arg_token6] = ACTIONS(62),
    [aux_sym_opcode_with_arg_token7] = ACTIONS(62),
    [aux_sym_opcode_with_arg_token8] = ACTIONS(62),
    [aux_sym_opcode_jump_token1] = ACTIONS(62),
    [aux_sym_opcode_jump_token2] = ACTIONS(62),
    [aux_sym_opcode_jump_token3] = ACTIONS(62),
    [sym_identifier] = ACTIONS(62),
    [aux_sym_number_token1] = ACTIONS(62),
    [aux_sym_number_token2] = ACTIONS(60),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(64),
    [sym_comment] = ACTIONS(64),
    [aux_sym_opcode_no_arg_token1] = ACTIONS(66),
    [aux_sym_opcode_no_arg_token2] = ACTIONS(66),
    [aux_sym_opcode_no_arg_token3] = ACTIONS(66),
    [aux_sym_opcode_no_arg_token4] = ACTIONS(66),
    [aux_sym_opcode_no_arg_token5] = ACTIONS(66),
    [aux_sym_opcode_no_arg_token6] = ACTIONS(66),
    [aux_sym_opcode_no_arg_token7] = ACTIONS(66),
    [aux_sym_opcode_no_arg_token8] = ACTIONS(66),
    [aux_sym_opcode_no_arg_token9] = ACTIONS(66),
    [aux_sym_opcode_no_arg_token10] = ACTIONS(66),
    [aux_sym_opcode_no_arg_token11] = ACTIONS(66),
    [aux_sym_opcode_no_arg_token12] = ACTIONS(66),
    [aux_sym_opcode_no_arg_token13] = ACTIONS(66),
    [aux_sym_opcode_no_arg_token14] = ACTIONS(66),
    [aux_sym_opcode_no_arg_token15] = ACTIONS(66),
    [aux_sym_opcode_no_arg_token16] = ACTIONS(66),
    [aux_sym_opcode_no_arg_token17] = ACTIONS(66),
    [aux_sym_opcode_no_arg_token18] = ACTIONS(66),
    [aux_sym_opcode_no_arg_token19] = ACTIONS(66),
    [aux_sym_opcode_with_arg_token1] = ACTIONS(66),
    [aux_sym_opcode_with_arg_token2] = ACTIONS(66),
    [aux_sym_opcode_with_arg_token3] = ACTIONS(66),
    [aux_sym_opcode_with_arg_token4] = ACTIONS(66),
    [aux_sym_opcode_with_arg_token5] = ACTIONS(66),
    [aux_sym_opcode_with_arg_token6] = ACTIONS(66),
    [aux_sym_opcode_with_arg_token7] = ACTIONS(66),
    [aux_sym_opcode_with_arg_token8] = ACTIONS(66),
    [aux_sym_opcode_jump_token1] = ACTIONS(66),
    [aux_sym_opcode_jump_token2] = ACTIONS(66),
    [aux_sym_opcode_jump_token3] = ACTIONS(66),
    [sym_identifier] = ACTIONS(66),
    [aux_sym_number_token1] = ACTIONS(66),
    [aux_sym_number_token2] = ACTIONS(64),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(46),
    [sym_comment] = ACTIONS(46),
    [aux_sym_opcode_no_arg_token1] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token2] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token3] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token4] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token5] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token6] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token7] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token8] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token9] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token10] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token11] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token12] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token13] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token14] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token15] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token16] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token17] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token18] = ACTIONS(50),
    [aux_sym_opcode_no_arg_token19] = ACTIONS(50),
    [aux_sym_opcode_with_arg_token1] = ACTIONS(50),
    [aux_sym_opcode_with_arg_token2] = ACTIONS(50),
    [aux_sym_opcode_with_arg_token3] = ACTIONS(50),
    [aux_sym_opcode_with_arg_token4] = ACTIONS(50),
    [aux_sym_opcode_with_arg_token5] = ACTIONS(50),
    [aux_sym_opcode_with_arg_token6] = ACTIONS(50),
    [aux_sym_opcode_with_arg_token7] = ACTIONS(50),
    [aux_sym_opcode_with_arg_token8] = ACTIONS(50),
    [aux_sym_opcode_jump_token1] = ACTIONS(50),
    [aux_sym_opcode_jump_token2] = ACTIONS(50),
    [aux_sym_opcode_jump_token3] = ACTIONS(50),
    [sym_identifier] = ACTIONS(50),
    [aux_sym_number_token1] = ACTIONS(50),
    [aux_sym_number_token2] = ACTIONS(46),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(68),
    [sym_comment] = ACTIONS(68),
    [aux_sym_opcode_no_arg_token1] = ACTIONS(70),
    [aux_sym_opcode_no_arg_token2] = ACTIONS(70),
    [aux_sym_opcode_no_arg_token3] = ACTIONS(70),
    [aux_sym_opcode_no_arg_token4] = ACTIONS(70),
    [aux_sym_opcode_no_arg_token5] = ACTIONS(70),
    [aux_sym_opcode_no_arg_token6] = ACTIONS(70),
    [aux_sym_opcode_no_arg_token7] = ACTIONS(70),
    [aux_sym_opcode_no_arg_token8] = ACTIONS(70),
    [aux_sym_opcode_no_arg_token9] = ACTIONS(70),
    [aux_sym_opcode_no_arg_token10] = ACTIONS(70),
    [aux_sym_opcode_no_arg_token11] = ACTIONS(70),
    [aux_sym_opcode_no_arg_token12] = ACTIONS(70),
    [aux_sym_opcode_no_arg_token13] = ACTIONS(70),
    [aux_sym_opcode_no_arg_token14] = ACTIONS(70),
    [aux_sym_opcode_no_arg_token15] = ACTIONS(70),
    [aux_sym_opcode_no_arg_token16] = ACTIONS(70),
    [aux_sym_opcode_no_arg_token17] = ACTIONS(70),
    [aux_sym_opcode_no_arg_token18] = ACTIONS(70),
    [aux_sym_opcode_no_arg_token19] = ACTIONS(70),
    [aux_sym_opcode_with_arg_token1] = ACTIONS(70),
    [aux_sym_opcode_with_arg_token2] = ACTIONS(70),
    [aux_sym_opcode_with_arg_token3] = ACTIONS(70),
    [aux_sym_opcode_with_arg_token4] = ACTIONS(70),
    [aux_sym_opcode_with_arg_token5] = ACTIONS(70),
    [aux_sym_opcode_with_arg_token6] = ACTIONS(70),
    [aux_sym_opcode_with_arg_token7] = ACTIONS(70),
    [aux_sym_opcode_with_arg_token8] = ACTIONS(70),
    [aux_sym_opcode_jump_token1] = ACTIONS(70),
    [aux_sym_opcode_jump_token2] = ACTIONS(70),
    [aux_sym_opcode_jump_token3] = ACTIONS(70),
    [sym_identifier] = ACTIONS(70),
    [aux_sym_number_token1] = ACTIONS(70),
    [aux_sym_number_token2] = ACTIONS(68),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(72),
    [sym_comment] = ACTIONS(72),
    [aux_sym_opcode_no_arg_token1] = ACTIONS(74),
    [aux_sym_opcode_no_arg_token2] = ACTIONS(74),
    [aux_sym_opcode_no_arg_token3] = ACTIONS(74),
    [aux_sym_opcode_no_arg_token4] = ACTIONS(74),
    [aux_sym_opcode_no_arg_token5] = ACTIONS(74),
    [aux_sym_opcode_no_arg_token6] = ACTIONS(74),
    [aux_sym_opcode_no_arg_token7] = ACTIONS(74),
    [aux_sym_opcode_no_arg_token8] = ACTIONS(74),
    [aux_sym_opcode_no_arg_token9] = ACTIONS(74),
    [aux_sym_opcode_no_arg_token10] = ACTIONS(74),
    [aux_sym_opcode_no_arg_token11] = ACTIONS(74),
    [aux_sym_opcode_no_arg_token12] = ACTIONS(74),
    [aux_sym_opcode_no_arg_token13] = ACTIONS(74),
    [aux_sym_opcode_no_arg_token14] = ACTIONS(74),
    [aux_sym_opcode_no_arg_token15] = ACTIONS(74),
    [aux_sym_opcode_no_arg_token16] = ACTIONS(74),
    [aux_sym_opcode_no_arg_token17] = ACTIONS(74),
    [aux_sym_opcode_no_arg_token18] = ACTIONS(74),
    [aux_sym_opcode_no_arg_token19] = ACTIONS(74),
    [aux_sym_opcode_with_arg_token1] = ACTIONS(74),
    [aux_sym_opcode_with_arg_token2] = ACTIONS(74),
    [aux_sym_opcode_with_arg_token3] = ACTIONS(74),
    [aux_sym_opcode_with_arg_token4] = ACTIONS(74),
    [aux_sym_opcode_with_arg_token5] = ACTIONS(74),
    [aux_sym_opcode_with_arg_token6] = ACTIONS(74),
    [aux_sym_opcode_with_arg_token7] = ACTIONS(74),
    [aux_sym_opcode_with_arg_token8] = ACTIONS(74),
    [aux_sym_opcode_jump_token1] = ACTIONS(74),
    [aux_sym_opcode_jump_token2] = ACTIONS(74),
    [aux_sym_opcode_jump_token3] = ACTIONS(74),
    [sym_identifier] = ACTIONS(74),
    [aux_sym_number_token1] = ACTIONS(74),
    [aux_sym_number_token2] = ACTIONS(72),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(15), 1,
      aux_sym_number_token1,
    ACTIONS(17), 1,
      aux_sym_number_token2,
    ACTIONS(76), 1,
      sym_identifier,
    STATE(9), 1,
      sym_number,
    STATE(11), 1,
      sym_argument,
  [16] = 2,
    ACTIONS(80), 1,
      aux_sym_number_token1,
    ACTIONS(78), 2,
      sym_identifier,
      aux_sym_number_token2,
  [24] = 2,
    ACTIONS(84), 1,
      aux_sym_number_token1,
    ACTIONS(82), 2,
      sym_identifier,
      aux_sym_number_token2,
  [32] = 1,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(12)] = 0,
  [SMALL_STATE(13)] = 16,
  [SMALL_STATE(14)] = 24,
  [SMALL_STATE(15)] = 32,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_argument, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opcode_no_arg, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opcode_no_arg, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syscall_arg, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_syscall_arg, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_instruction, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label_definition, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_label_definition, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_instruction, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opcode_with_arg, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opcode_with_arg, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_opcode_jump, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_opcode_jump, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_twn(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "twn",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
